M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu22.04.1} date Thu 22 Sep 2022 09:51:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-22T09:51:43+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X20.0Y-20.0
X20.0Y-107.0
X108.0Y-20.0
X108.0Y-107.0
T0
M30
