M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu22.04.1} date Sat 03 Sep 2022 23:28:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-03T23:28:11+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X20.0Y-20.0
X20.0Y-93.6
X96.0Y-20.0
X96.0Y-93.6
T0
M30
